-- 실행계획 만들기
EXPLAIN PLAN FOR
SELECT * FROM T_ORD WHERE ORD_SEQ = 4;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());



-- 오퍼레이션 순서 파악하기
EXPLAIN PLAN FOR
SELECT *
FROM T_ORD T1
    , M_CUS T2
WHERE T1.CUS_ID = T2.CUS_ID
AND T1.ORD_DT >= TO_DATE('20170101', 'YYYYMMDD')
AND T1.ORD_DT < TO_DATE('20170201', 'YYYYMMDD')
AND T2.CUS_GD ='A';

SELECT *
FROM TABLE(DBMS_XPLAN.DISPLAY());



EXPLAIN PLAN FOR
SELECT  T3.ITM_ID ,SUM(T2.ORD_QTY) ORD_QTY
FROM    T_ORD T1
        ,T_ORD_DET T2
        ,M_ITM T3
WHERE   T1.ORD_SEQ = T2.ORD_SEQ
AND     T1.ORD_DT >= TO_DATE('20170101','YYYYMMDD')
AND     T1.ORD_DT < TO_DATE('20170201','YYYYMMDD')
AND     T2.ITM_ID = T3.ITM_ID
AND     T3.ITM_TP = 'ELEC'
GROUP BY T3.ITM_ID;

SELECT  * FROM TABLE(DBMS_XPLAN.DISPLAY());


-- 실행계획 만들기
SELECT  /*+ GATHER_PLAN_STATISTICS */
		*
FROM    T_ORD T1
        ,M_CUS T2
WHERE   T1.CUS_ID = T2.CUS_ID
AND     T1.ORD_DT >= TO_DATE('20170101','YYYYMMDD')
AND     T1.ORD_DT < TO_DATE('20170201','YYYYMMDD')
AND     T2.CUS_GD = 'A';

SELECT  T1.SQL_ID ,T1.CHILD_NUMBER ,T1.SQL_TEXT
FROM    V$SQL T1
WHERE   T1.SQL_TEXT LIKE '%GATHER_PLAN_STATISTICS%'
ORDER BY T1.LAST_ACTIVE_TIME DESC;


SELECT  *
FROM    TABLE(DBMS_XPLAN.DISPLAY_CURSOR('ad1p7thaxs821',0,'ALLSTATS LAST'));
